source 'https://github.com/CocoaPods/Specs.git'

target 'SPXDataValidators', :exclusive => true do
  pod "SPXDataValidators", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SPXDataValidators", :path => "../"

  pod 'Kiwi'
end
