source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Warrant_Example', :exclusive => true do
  pod 'Warrant', :path => '../'
  pod 'SPXControls'
end

target 'Warrant_Tests', :exclusive => true do
  pod 'Warrant', :path => '../'

  
end
